//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrosLista {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrosLista() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Common.Resources.ErrosLista", typeof(ErrosLista).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Codio da Cidade, Inválido!.
        /// </summary>
        public static string Cidades_Codigo {
            get {
                return ResourceManager.GetString("Cidades_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome da Cidade, Invalido!.
        /// </summary>
        public static string Cidades_Nome {
            get {
                return ResourceManager.GetString("Cidades_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo UF, Inválido!.
        /// </summary>
        public static string Cidades_UF {
            get {
                return ResourceManager.GetString("Cidades_UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Bairro, Inválido!.
        /// </summary>
        public static string Clientes_Bairro {
            get {
                return ResourceManager.GetString("Clientes_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Cep, Inválido!.
        /// </summary>
        public static string Clientes_Cep {
            get {
                return ResourceManager.GetString("Clientes_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CNPJ/CPF, Inválido!.
        /// </summary>
        public static string Clientes_CNPJorCPF {
            get {
                return ResourceManager.GetString("Clientes_CNPJorCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Complemento, Inválido!.
        /// </summary>
        public static string Clientes_Complemento {
            get {
                return ResourceManager.GetString("Clientes_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CPF, Inválido!.
        /// </summary>
        public static string Clientes_CPF {
            get {
                return ResourceManager.GetString("Clientes_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Inválido!.
        /// </summary>
        public static string Clientes_Id {
            get {
                return ResourceManager.GetString("Clientes_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Inscrição, Inválido!.
        /// </summary>
        public static string Clientes_Inscricao {
            get {
                return ResourceManager.GetString("Clientes_Inscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome do Cliente, Inválido!.
        /// </summary>
        public static string Clientes_Nome {
            get {
                return ResourceManager.GetString("Clientes_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome do Serviço, Inválido!.
        /// </summary>
        public static string Clientes_NomeServico {
            get {
                return ResourceManager.GetString("Clientes_NomeServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Numero do Logradouro, Inválido!.
        /// </summary>
        public static string Clientes_NumLogradouro {
            get {
                return ResourceManager.GetString("Clientes_NumLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo Logradouro, Inválido!.
        /// </summary>
        public static string Clientes_TipoLogradouro {
            get {
                return ResourceManager.GetString("Clientes_TipoLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo Pessoa, Inválido!.
        /// </summary>
        public static string Clientes_TipoPessoa {
            get {
                return ResourceManager.GetString("Clientes_TipoPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Valor, Inválido!.
        /// </summary>
        public static string Clientes_Valor {
            get {
                return ResourceManager.GetString("Clientes_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Email, inválido!.
        /// </summary>
        public static string Email_Invalido {
            get {
                return ResourceManager.GetString("Email_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Assinatura, Inválido!.
        /// </summary>
        public static string NotasFiscais_Assinatura {
            get {
                return ResourceManager.GetString("NotasFiscais_Assinatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data de Emissão, Inválido!.
        /// </summary>
        public static string NotasFiscais_DataEmissao {
            get {
                return ResourceManager.GetString("NotasFiscais_DataEmissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Lote, Inválido!.
        /// </summary>
        public static string NotasFiscais_Lote {
            get {
                return ResourceManager.GetString("NotasFiscais_Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Motivo, Inválido!.
        /// </summary>
        public static string NotasFiscais_Motivo {
            get {
                return ResourceManager.GetString("NotasFiscais_Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Numero da Nota Fiscal, Inválido!.
        /// </summary>
        public static string NotasFiscais_Numero {
            get {
                return ResourceManager.GetString("NotasFiscais_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Protocolo, Inválido!.
        /// </summary>
        public static string NotasFiscais_Protocolo {
            get {
                return ResourceManager.GetString("NotasFiscais_Protocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo RPS, Inválido!.
        /// </summary>
        public static string NotasFiscais_RPS {
            get {
                return ResourceManager.GetString("NotasFiscais_RPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Status da Nota Fiscal, Inválido!.
        /// </summary>
        public static string NotasFiscais_Status {
            get {
                return ResourceManager.GetString("NotasFiscais_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Verificação, Inválido!.
        /// </summary>
        public static string NotasFiscais_Verificacao {
            get {
                return ResourceManager.GetString("NotasFiscais_Verificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Codigo, Inválido!.
        /// </summary>
        public static string RegimeClientes_Codigo {
            get {
                return ResourceManager.GetString("RegimeClientes_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Deduçoes, Inválido!.
        /// </summary>
        public static string RegimeClientes_Deducoes {
            get {
                return ResourceManager.GetString("RegimeClientes_Deducoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Regime Tributário, Inválido!.
        /// </summary>
        public static string RegimeClientes_Nome {
            get {
                return ResourceManager.GetString("RegimeClientes_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tributo, Inválido!.
        /// </summary>
        public static string RegimeClientes_Tributo {
            get {
                return ResourceManager.GetString("RegimeClientes_Tributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo de Cliente, Inválido!.
        /// </summary>
        public static string TipoClientes_Nome {
            get {
                return ResourceManager.GetString("TipoClientes_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Confirmar Senha, Inválido!.
        /// </summary>
        public static string Usuarios_ConfirmarSenha {
            get {
                return ResourceManager.GetString("Usuarios_ConfirmarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Perfil, Inválido!.
        /// </summary>
        public static string Usuarios_Perfil {
            get {
                return ResourceManager.GetString("Usuarios_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Senha, Invalido!.
        /// </summary>
        public static string Usuarios_Senha {
            get {
                return ResourceManager.GetString("Usuarios_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Usuário, Inválido!.
        /// </summary>
        public static string Usuarios_Usuario {
            get {
                return ResourceManager.GetString("Usuarios_Usuario", resourceCulture);
            }
        }
    }
}
